// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CrationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cration() {
    driver.get("https://mohamedmamdouh1999.github.io/Products_CRUDS/");
    driver.manage().window().setSize(new Dimension(1696, 1018));
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Wow");
    driver.findElement(By.id("inputPrice")).click();
    driver.findElement(By.id("inputPrice")).sendKeys("1000");
    driver.findElement(By.id("inputCondition")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCondition"));
      dropdown.findElement(By.xpath("//option[. = 'Excellent']")).click();
    }
    driver.findElement(By.id("btnAdd")).click();
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Mid");
    driver.findElement(By.id("inputPrice")).click();
    driver.findElement(By.id("inputPrice")).sendKeys("500");
    driver.findElement(By.cssSelector(".p-2:nth-child(1)")).click();
    driver.findElement(By.id("inputCategory")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCategory"));
      dropdown.findElement(By.xpath("//option[. = 'TV']")).click();
    }
    driver.findElement(By.id("inputCondition")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCondition"));
      dropdown.findElement(By.xpath("//option[. = 'Good']")).click();
    }
    driver.findElement(By.id("btnAdd")).click();
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Bad tv");
    driver.findElement(By.id("inputPrice")).click();
    driver.findElement(By.id("inputPrice")).sendKeys("50");
    driver.findElement(By.id("inputCategory")).click();
    driver.findElement(By.id("inputPrice")).click();
    driver.findElement(By.id("inputPrice")).sendKeys("100");
    driver.findElement(By.cssSelector(".p-2:nth-child(1)")).click();
    driver.findElement(By.id("inputCategory")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCategory"));
      dropdown.findElement(By.xpath("//option[. = 'TV']")).click();
    }
    driver.findElement(By.id("inputCondition")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCondition"));
      dropdown.findElement(By.xpath("//option[. = 'Bad']")).click();
    }
    driver.findElement(By.id("btnAdd")).click();
    {
      WebElement element = driver.findElement(By.id("btnAdd"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Wow laptop");
    driver.findElement(By.id("inputPrice")).click();
    driver.findElement(By.id("inputPrice")).sendKeys("1000");
    driver.findElement(By.id("inputCategory")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCategory"));
      dropdown.findElement(By.xpath("//option[. = 'LAPTOB']")).click();
    }
    driver.findElement(By.id("inputCondition")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCondition"));
      dropdown.findElement(By.xpath("//option[. = 'Excellent']")).click();
    }
    driver.findElement(By.id("btnAdd")).click();
    {
      WebElement element = driver.findElement(By.id("btnAdd"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".p-2:nth-child(1)")).click();
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Mid Laptop");
    driver.findElement(By.id("inputPrice")).click();
    driver.findElement(By.id("inputPrice")).sendKeys("500");
    driver.findElement(By.id("inputCategory")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCategory"));
      dropdown.findElement(By.xpath("//option[. = 'LAPTOB']")).click();
    }
    driver.findElement(By.id("inputCondition")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCondition"));
      dropdown.findElement(By.xpath("//option[. = 'Good']")).click();
    }
    driver.findElement(By.id("btnAdd")).click();
    {
      WebElement element = driver.findElement(By.id("btnAdd"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Bad Laptop");
    driver.findElement(By.id("inputPrice")).click();
    driver.findElement(By.id("inputPrice")).sendKeys("100");
    driver.findElement(By.id("inputCategory")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCategory"));
      dropdown.findElement(By.xpath("//option[. = 'LAPTOB']")).click();
    }
    driver.findElement(By.id("inputCondition")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCondition"));
      dropdown.findElement(By.xpath("//option[. = 'Bad']")).click();
    }
    driver.findElement(By.id("btnAdd")).click();
    {
      WebElement element = driver.findElement(By.id("btnAdd"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputCondition")).click();
    driver.findElement(By.id("inputCategory")).click();
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Wow Mobile");
    driver.findElement(By.id("inputPrice")).click();
    driver.findElement(By.id("inputPrice")).sendKeys("1000");
    driver.findElement(By.id("inputCategory")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCategory"));
      dropdown.findElement(By.xpath("//option[. = 'MOBILE']")).click();
    }
    driver.findElement(By.id("inputCondition")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCondition"));
      dropdown.findElement(By.xpath("//option[. = 'Excellent']")).click();
    }
    driver.findElement(By.id("btnAdd")).click();
    {
      WebElement element = driver.findElement(By.id("btnAdd"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Mif Mobile");
    driver.findElement(By.id("inputPrice")).click();
    driver.findElement(By.id("inputPrice")).sendKeys("500");
    driver.findElement(By.id("inputCategory")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCategory"));
      dropdown.findElement(By.xpath("//option[. = 'MOBILE']")).click();
    }
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Mid Mobile");
    driver.findElement(By.id("inputCondition")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCondition"));
      dropdown.findElement(By.xpath("//option[. = 'Good']")).click();
    }
    driver.findElement(By.id("btnAdd")).click();
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("Bad Mobile");
    driver.findElement(By.id("inputPrice")).click();
    driver.findElement(By.id("inputPrice")).sendKeys("100");
    driver.findElement(By.id("inputCategory")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCategory"));
      dropdown.findElement(By.xpath("//option[. = 'MOBILE']")).click();
    }
    driver.findElement(By.id("inputCondition")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCondition"));
      dropdown.findElement(By.xpath("//option[. = 'Bad']")).click();
    }
    driver.findElement(By.id("btnAdd")).click();
    {
      WebElement element = driver.findElement(By.id("btnAdd"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("btnClear")).click();
    driver.findElement(By.id("btnClear")).click();
  }
}
