# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestModification():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_modification(self):
    self.driver.get("https://mohamedmamdouh1999.github.io/Products_CRUDS/")
    self.driver.set_window_size(1696, 1018)
    self.driver.find_element(By.ID, "inputName").click()
    self.driver.find_element(By.ID, "inputName").send_keys("Samsung")
    self.driver.find_element(By.ID, "inputPrice").click()
    self.driver.find_element(By.ID, "inputPrice").send_keys("1000")
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .me-2").click()
    self.driver.find_element(By.ID, "inputCondition").click()
    dropdown = self.driver.find_element(By.ID, "inputCondition")
    dropdown.find_element(By.XPATH, "//option[. = 'Excellent']").click()
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .me-2").click()
    self.driver.find_element(By.ID, "inputCondition").click()
    dropdown = self.driver.find_element(By.ID, "inputCondition")
    dropdown.find_element(By.XPATH, "//option[. = 'Bad']").click()
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .me-2").click()
    self.driver.find_element(By.ID, "inputCategory").click()
    dropdown = self.driver.find_element(By.ID, "inputCategory")
    dropdown.find_element(By.XPATH, "//option[. = 'MOBILE']").click()
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .me-2").click()
    self.driver.find_element(By.ID, "inputCategory").click()
    dropdown = self.driver.find_element(By.ID, "inputCategory")
    dropdown.find_element(By.XPATH, "//option[. = 'LAPTOB']").click()
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .me-2").click()
    self.driver.find_element(By.ID, "inputPrice").click()
    self.driver.find_element(By.ID, "inputPrice").send_keys("1999999999999999999999")
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .me-2").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.ID, "inputName").send_keys("Apple")
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .text-danger").click()
  
