# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSuppression():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_suppression(self):
    self.driver.get("https://mohamedmamdouh1999.github.io/Products_CRUDS/")
    self.driver.set_window_size(1260, 751)
    self.driver.find_element(By.ID, "btnClear").click()
    self.driver.find_element(By.ID, "btnClear").click()
    self.driver.find_element(By.ID, "btnClear").click()
    self.driver.find_element(By.ID, "btnClear").click()
    element = self.driver.find_element(By.ID, "btnClear")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "btnClear").click()
    self.driver.find_element(By.ID, "btnClear").click()
    self.driver.find_element(By.ID, "btnClear").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .text-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .text-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .text-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .text-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .text-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .text-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .text-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .text-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-danger").click()
  
